// UI string translations. Merged into the catalog in ui-strings.ts.
export const dicts: Record<string, Record<string, string>> = {
	it: {
		onThisPage: 'In questa pagina',
		previous: 'Precedente',
		next: 'Successivo',
		searchDocs: 'Cerca…',
		searchPlaceholder: 'Cerca nella documentazione…',
		searchStart: 'Inizia a digitare per cercare.',
		searchNoResults: 'Nessun risultato',
		searchLoading: 'Caricamento dell\'indice…',
		getStarted: 'Inizia',
		viewSource: 'Vedi il codice sorgente',
		page: 'pagina',
		pages: 'pagine',
		builtWith: 'realizzato con',
		editOnGithub: 'Modifica su GitHub',
		poweredBy: 'Basato su',
		listAnd: 'e',
		renderingDiagram: 'Rendering del diagramma…',
		copyCode: 'Copia il codice',
		copied: 'Copiato',
		language: 'Lingua'
	},
	pt: {
		onThisPage: 'Nesta página',
		previous: 'Anterior',
		next: 'Próximo',
		searchDocs: 'Pesquisar…',
		searchPlaceholder: 'Pesquisar na documentação…',
		searchStart: 'Comece a digitar para pesquisar.',
		searchNoResults: 'Sem resultados',
		searchLoading: 'A carregar o índice…',
		getStarted: 'Começar',
		viewSource: 'Ver o código-fonte',
		page: 'página',
		pages: 'páginas',
		builtWith: 'criado com',
		editOnGithub: 'Editar no GitHub',
		poweredBy: 'Desenvolvido com',
		listAnd: 'e',
		renderingDiagram: 'A renderizar o diagrama…',
		copyCode: 'Copiar código',
		copied: 'Copiado',
		language: 'Idioma'
	},
	ca: {
		onThisPage: 'En aquesta pàgina',
		previous: 'Anterior',
		next: 'Següent',
		searchDocs: 'Cerca…',
		searchPlaceholder: 'Cerca a la documentació…',
		searchStart: 'Comença a escriure per cercar.',
		searchNoResults: 'Cap resultat',
		searchLoading: 'S\'està carregant l\'índex…',
		getStarted: 'Comença',
		viewSource: 'Mostra el codi font',
		page: 'pàgina',
		pages: 'pàgines',
		builtWith: 'fet amb',
		editOnGithub: 'Edita a GitHub',
		poweredBy: 'Funciona amb',
		listAnd: 'i',
		renderingDiagram: 'S\'està renderitzant el diagrama…',
		copyCode: 'Copia el codi',
		copied: 'Copiat',
		language: 'Idioma'
	},
	gl: {
		onThisPage: 'Nesta páxina',
		previous: 'Anterior',
		next: 'Seguinte',
		searchDocs: 'Buscar…',
		searchPlaceholder: 'Buscar na documentación…',
		searchStart: 'Comeza a escribir para buscar.',
		searchNoResults: 'Sen resultados',
		searchLoading: 'Cargando o índice…',
		getStarted: 'Comezar',
		viewSource: 'Ver o código fonte',
		page: 'páxina',
		pages: 'páxinas',
		builtWith: 'feito con',
		editOnGithub: 'Editar en GitHub',
		poweredBy: 'Funciona con',
		listAnd: 'e',
		renderingDiagram: 'Renderizando o diagrama…',
		copyCode: 'Copiar o código',
		copied: 'Copiado',
		language: 'Idioma'
	},
	ro: {
		onThisPage: 'Pe această pagină',
		previous: 'Anterior',
		next: 'Următor',
		searchDocs: 'Caută…',
		searchPlaceholder: 'Caută în documentație…',
		searchStart: 'Începe să tastezi pentru a căuta.',
		searchNoResults: 'Niciun rezultat',
		searchLoading: 'Se încarcă indexul…',
		getStarted: 'Începe',
		viewSource: 'Vezi codul sursă',
		page: 'pagină',
		pages: 'pagini',
		builtWith: 'creat cu',
		editOnGithub: 'Editează pe GitHub',
		poweredBy: 'Susținut de',
		listAnd: 'și',
		renderingDiagram: 'Se randează diagrama…',
		copyCode: 'Copiază codul',
		copied: 'Copiat',
		language: 'Limbă'
	},
	el: {
		onThisPage: 'Σε αυτήν τη σελίδα',
		previous: 'Προηγούμενο',
		next: 'Επόμενο',
		searchDocs: 'Αναζήτηση…',
		searchPlaceholder: 'Αναζήτηση στην τεκμηρίωση…',
		searchStart: 'Ξεκινήστε να πληκτρολογείτε για αναζήτηση.',
		searchNoResults: 'Κανένα αποτέλεσμα',
		searchLoading: 'Φόρτωση ευρετηρίου…',
		getStarted: 'Ξεκινήστε',
		viewSource: 'Προβολή πηγαίου κώδικα',
		page: 'σελίδα',
		pages: 'σελίδες',
		builtWith: 'φτιαγμένο με',
		editOnGithub: 'Επεξεργασία στο GitHub',
		poweredBy: 'Με την υποστήριξη του',
		listAnd: 'και',
		renderingDiagram: 'Απόδοση διαγράμματος…',
		copyCode: 'Αντιγραφή κώδικα',
		copied: 'Αντιγράφηκε',
		language: 'Γλώσσα'
	},
	fi: {
		onThisPage: 'Tällä sivulla',
		previous: 'Edellinen',
		next: 'Seuraava',
		searchDocs: 'Hae…',
		searchPlaceholder: 'Hae dokumentaatiosta…',
		searchStart: 'Aloita kirjoittaminen hakeaksesi.',
		searchNoResults: 'Ei tuloksia',
		searchLoading: 'Ladataan hakemistoa…',
		getStarted: 'Aloita',
		viewSource: 'Näytä lähdekoodi',
		page: 'sivu',
		pages: 'sivua',
		builtWith: 'tehty käyttäen',
		editOnGithub: 'Muokkaa GitHubissa',
		poweredBy: 'Taustalla',
		listAnd: 'ja',
		renderingDiagram: 'Renderöidään kaaviota…',
		copyCode: 'Kopioi koodi',
		copied: 'Kopioitu',
		language: 'Kieli'
	},
	hu: {
		onThisPage: 'Ezen az oldalon',
		previous: 'Előző',
		next: 'Következő',
		searchDocs: 'Keresés…',
		searchPlaceholder: 'Keresés a dokumentációban…',
		searchStart: 'Kezdj el gépelni a kereséshez.',
		searchNoResults: 'Nincs találat',
		searchLoading: 'Keresési index betöltése…',
		getStarted: 'Kezdés',
		viewSource: 'Forráskód megtekintése',
		page: 'oldal',
		pages: 'oldal',
		builtWith: 'készült ezzel:',
		editOnGithub: 'Szerkesztés a GitHubon',
		poweredBy: 'Működteti:',
		listAnd: 'és',
		renderingDiagram: 'Diagram megjelenítése…',
		copyCode: 'Kód másolása',
		copied: 'Másolva',
		language: 'Nyelv'
	},
	eu: {
		onThisPage: 'Orrialde honetan',
		previous: 'Aurrekoa',
		next: 'Hurrengoa',
		searchDocs: 'Bilatu…',
		searchPlaceholder: 'Bilatu dokumentazioan…',
		searchStart: 'Hasi idazten bilatzeko.',
		searchNoResults: 'Emaitzarik ez',
		searchLoading: 'Bilaketa-indizea kargatzen…',
		getStarted: 'Hasi',
		viewSource: 'Ikusi iturburu-kodea',
		page: 'orrialde',
		pages: 'orrialde',
		builtWith: 'honekin egina:',
		editOnGithub: 'Editatu GitHuben',
		poweredBy: 'Honako hauen bidez:',
		listAnd: 'eta',
		renderingDiagram: 'Diagrama errendatzen…',
		copyCode: 'Kopiatu kodea',
		copied: 'Kopiatuta',
		language: 'Hizkuntza'
	}
};
