// UI string translations. Merged into the catalog in ui-strings.ts.
export const dicts: Record<string, Record<string, string>> = {
	pl: {
		onThisPage: 'Na tej stronie',
		previous: 'Poprzednia',
		next: 'Następna',
		searchDocs: 'Szukaj…',
		searchPlaceholder: 'Przeszukaj dokumentację…',
		searchStart: 'Zacznij pisać, aby wyszukać.',
		searchNoResults: 'Brak wyników',
		searchLoading: 'Wczytywanie indeksu wyszukiwania…',
		getStarted: 'Rozpocznij',
		viewSource: 'Zobacz kod źródłowy',
		page: 'strona',
		pages: 'strony',
		builtWith: 'utworzono za pomocą',
		editOnGithub: 'Edytuj na GitHubie',
		poweredBy: 'Działa dzięki',
		listAnd: 'i',
		renderingDiagram: 'Renderowanie diagramu…',
		copyCode: 'Kopiuj kod',
		copied: 'Skopiowano',
		language: 'Język'
	},
	ru: {
		onThisPage: 'На этой странице',
		previous: 'Назад',
		next: 'Далее',
		searchDocs: 'Поиск…',
		searchPlaceholder: 'Поиск по документации…',
		searchStart: 'Начните вводить, чтобы найти.',
		searchNoResults: 'Ничего не найдено',
		searchLoading: 'Загрузка индекса поиска…',
		getStarted: 'Начать',
		viewSource: 'Исходный код',
		page: 'страница',
		pages: 'страниц',
		builtWith: 'создано с помощью',
		editOnGithub: 'Редактировать на GitHub',
		poweredBy: 'Работает на',
		listAnd: 'и',
		renderingDiagram: 'Отрисовка диаграммы…',
		copyCode: 'Копировать код',
		copied: 'Скопировано',
		language: 'Язык'
	},
	uk: {
		onThisPage: 'На цій сторінці',
		previous: 'Назад',
		next: 'Далі',
		searchDocs: 'Пошук…',
		searchPlaceholder: 'Пошук у документації…',
		searchStart: 'Почніть вводити, щоб шукати.',
		searchNoResults: 'Нічого не знайдено',
		searchLoading: 'Завантаження індексу пошуку…',
		getStarted: 'Почати',
		viewSource: 'Переглянути код',
		page: 'сторінка',
		pages: 'сторінок',
		builtWith: 'створено за допомогою',
		editOnGithub: 'Редагувати на GitHub',
		poweredBy: 'Працює на',
		listAnd: 'та',
		renderingDiagram: 'Рендеринг діаграми…',
		copyCode: 'Копіювати код',
		copied: 'Скопійовано',
		language: 'Мова'
	},
	cs: {
		onThisPage: 'Na této stránce',
		previous: 'Předchozí',
		next: 'Další',
		searchDocs: 'Hledat…',
		searchPlaceholder: 'Prohledat dokumentaci…',
		searchStart: 'Začněte psát pro vyhledávání.',
		searchNoResults: 'Žádné výsledky',
		searchLoading: 'Načítání indexu vyhledávání…',
		getStarted: 'Začít',
		viewSource: 'Zobrazit zdroj',
		page: 'stránka',
		pages: 'stránky',
		builtWith: 'vytvořeno pomocí',
		editOnGithub: 'Upravit na GitHubu',
		poweredBy: 'Postaveno na',
		listAnd: 'a',
		renderingDiagram: 'Vykreslování diagramu…',
		copyCode: 'Kopírovat kód',
		copied: 'Zkopírováno',
		language: 'Jazyk'
	},
	sk: {
		onThisPage: 'Na tejto stránke',
		previous: 'Predchádzajúca',
		next: 'Ďalšia',
		searchDocs: 'Hľadať…',
		searchPlaceholder: 'Prehľadať dokumentáciu…',
		searchStart: 'Začnite písať pre vyhľadávanie.',
		searchNoResults: 'Žiadne výsledky',
		searchLoading: 'Načítava sa index vyhľadávania…',
		getStarted: 'Začať',
		viewSource: 'Zobraziť zdroj',
		page: 'stránka',
		pages: 'stránky',
		builtWith: 'vytvorené pomocou',
		editOnGithub: 'Upraviť na GitHube',
		poweredBy: 'Beží na',
		listAnd: 'a',
		renderingDiagram: 'Vykresľovanie diagramu…',
		copyCode: 'Kopírovať kód',
		copied: 'Skopírované',
		language: 'Jazyk'
	},
	sl: {
		onThisPage: 'Na tej strani',
		previous: 'Prejšnja',
		next: 'Naslednja',
		searchDocs: 'Iskanje…',
		searchPlaceholder: 'Preišči dokumentacijo…',
		searchStart: 'Začnite tipkati za iskanje.',
		searchNoResults: 'Ni rezultatov',
		searchLoading: 'Nalaganje iskalnega indeksa…',
		getStarted: 'Začni',
		viewSource: 'Prikaži izvorno kodo',
		page: 'stran',
		pages: 'strani',
		builtWith: 'ustvarjeno z',
		editOnGithub: 'Uredi na GitHubu',
		poweredBy: 'Poganja',
		listAnd: 'in',
		renderingDiagram: 'Izrisovanje diagrama…',
		copyCode: 'Kopiraj kodo',
		copied: 'Kopirano',
		language: 'Jezik'
	},
	hr: {
		onThisPage: 'Na ovoj stranici',
		previous: 'Prethodna',
		next: 'Sljedeća',
		searchDocs: 'Pretraži…',
		searchPlaceholder: 'Pretraži dokumentaciju…',
		searchStart: 'Počnite tipkati za pretraživanje.',
		searchNoResults: 'Nema rezultata',
		searchLoading: 'Učitavanje indeksa pretraživanja…',
		getStarted: 'Započni',
		viewSource: 'Prikaži izvorni kod',
		page: 'stranica',
		pages: 'stranice',
		builtWith: 'izrađeno pomoću',
		editOnGithub: 'Uredi na GitHubu',
		poweredBy: 'Pokreće',
		listAnd: 'i',
		renderingDiagram: 'Iscrtavanje dijagrama…',
		copyCode: 'Kopiraj kod',
		copied: 'Kopirano',
		language: 'Jezik'
	},
	sr: {
		onThisPage: 'На овој страници',
		previous: 'Претходна',
		next: 'Следећа',
		searchDocs: 'Претрага…',
		searchPlaceholder: 'Претражи документацију…',
		searchStart: 'Почните да куцате за претрагу.',
		searchNoResults: 'Нема резултата',
		searchLoading: 'Учитавање индекса претраге…',
		getStarted: 'Започни',
		viewSource: 'Прикажи изворни код',
		page: 'страница',
		pages: 'странице',
		builtWith: 'направљено помоћу',
		editOnGithub: 'Уреди на GitHub-у',
		poweredBy: 'Покреће',
		listAnd: 'и',
		renderingDiagram: 'Исцртавање дијаграма…',
		copyCode: 'Копирај код',
		copied: 'Копирано',
		language: 'Језик'
	},
	bg: {
		onThisPage: 'На тази страница',
		previous: 'Назад',
		next: 'Напред',
		searchDocs: 'Търсене…',
		searchPlaceholder: 'Търсене в документацията…',
		searchStart: 'Започнете да пишете, за да търсите.',
		searchNoResults: 'Няма резултати',
		searchLoading: 'Зареждане на индекса за търсене…',
		getStarted: 'Започнете',
		viewSource: 'Преглед на кода',
		page: 'страница',
		pages: 'страници',
		builtWith: 'създадено с',
		editOnGithub: 'Редактиране в GitHub',
		poweredBy: 'Захранвано от',
		listAnd: 'и',
		renderingDiagram: 'Изобразяване на диаграмата…',
		copyCode: 'Копиране на кода',
		copied: 'Копирано',
		language: 'Език'
	},
	lt: {
		onThisPage: 'Šiame puslapyje',
		previous: 'Ankstesnis',
		next: 'Kitas',
		searchDocs: 'Ieškoti…',
		searchPlaceholder: 'Ieškoti dokumentacijoje…',
		searchStart: 'Pradėkite rašyti, kad ieškotumėte.',
		searchNoResults: 'Rezultatų nėra',
		searchLoading: 'Įkeliamas paieškos indeksas…',
		getStarted: 'Pradėti',
		viewSource: 'Peržiūrėti šaltinį',
		page: 'puslapis',
		pages: 'puslapiai',
		builtWith: 'sukurta su',
		editOnGithub: 'Redaguoti „GitHub“',
		poweredBy: 'Veikia su',
		listAnd: 'ir',
		renderingDiagram: 'Atvaizduojama diagrama…',
		copyCode: 'Kopijuoti kodą',
		copied: 'Nukopijuota',
		language: 'Kalba'
	},
	lv: {
		onThisPage: 'Šajā lapā',
		previous: 'Iepriekšējā',
		next: 'Nākamā',
		searchDocs: 'Meklēt…',
		searchPlaceholder: 'Meklēt dokumentācijā…',
		searchStart: 'Sāciet rakstīt, lai meklētu.',
		searchNoResults: 'Nav rezultātu',
		searchLoading: 'Notiek meklēšanas indeksa ielāde…',
		getStarted: 'Sākt',
		viewSource: 'Skatīt pirmkodu',
		page: 'lapa',
		pages: 'lapas',
		builtWith: 'izveidots ar',
		editOnGithub: 'Rediģēt GitHub',
		poweredBy: 'Darbojas ar',
		listAnd: 'un',
		renderingDiagram: 'Notiek diagrammas attēlošana…',
		copyCode: 'Kopēt kodu',
		copied: 'Nokopēts',
		language: 'Valoda'
	},
	et: {
		onThisPage: 'Sellel lehel',
		previous: 'Eelmine',
		next: 'Järgmine',
		searchDocs: 'Otsi…',
		searchPlaceholder: 'Otsi dokumentatsioonist…',
		searchStart: 'Otsimiseks alusta tippimist.',
		searchNoResults: 'Tulemusi pole',
		searchLoading: 'Otsinguindeksi laadimine…',
		getStarted: 'Alusta',
		viewSource: 'Vaata lähtekoodi',
		page: 'leht',
		pages: 'lehte',
		builtWith: 'loodud tööriistaga',
		editOnGithub: 'Muuda GitHubis',
		poweredBy: 'Töötab tänu',
		listAnd: 'ja',
		renderingDiagram: 'Diagrammi renderdamine…',
		copyCode: 'Kopeeri kood',
		copied: 'Kopeeritud',
		language: 'Keel'
	}
};
