// UI string translations. Merged into the catalog in ui-strings.ts.
export const dicts: Record<string, Record<string, string>> = {
	ja: {
		onThisPage: 'このページの内容',
		previous: '前へ',
		next: '次へ',
		searchDocs: 'ドキュメントを検索…',
		searchPlaceholder: 'ドキュメントを検索…',
		searchStart: '入力して検索を開始',
		searchNoResults: '結果なし',
		searchLoading: '検索インデックスを読み込み中…',
		getStarted: 'はじめる',
		viewSource: 'ソースを見る',
		page: 'ページ',
		pages: 'ページ',
		builtWith: '使用技術',
		editOnGithub: 'GitHub で編集',
		poweredBy: 'Powered by',
		listAnd: '、',
		renderingDiagram: '図を描画中…',
		copyCode: 'コードをコピー',
		copied: 'コピーしました',
		language: '言語'
	},
	zh: {
		onThisPage: '本页内容',
		previous: '上一页',
		next: '下一页',
		searchDocs: '搜索文档…',
		searchPlaceholder: '搜索文档…',
		searchStart: '输入以开始搜索',
		searchNoResults: '没有结果',
		searchLoading: '正在加载搜索索引…',
		getStarted: '开始使用',
		viewSource: '查看源码',
		page: '页',
		pages: '页',
		builtWith: '技术栈',
		editOnGithub: '在 GitHub 上编辑',
		poweredBy: '技术支持',
		listAnd: '和',
		renderingDiagram: '正在渲染图表…',
		copyCode: '复制代码',
		copied: '已复制',
		language: '语言'
	},
	ko: {
		onThisPage: '이 페이지의 내용',
		previous: '이전',
		next: '다음',
		searchDocs: '문서 검색…',
		searchPlaceholder: '문서 검색…',
		searchStart: '입력하여 검색을 시작하세요',
		searchNoResults: '결과 없음',
		searchLoading: '검색 색인을 불러오는 중…',
		getStarted: '시작하기',
		viewSource: '소스 보기',
		page: '페이지',
		pages: '페이지',
		builtWith: '사용 기술',
		editOnGithub: 'GitHub에서 편집',
		poweredBy: 'Powered by',
		listAnd: '및',
		renderingDiagram: '다이어그램 렌더링 중…',
		copyCode: '코드 복사',
		copied: '복사됨',
		language: '언어'
	},
	hi: {
		onThisPage: 'इस पेज पर',
		previous: 'पिछला',
		next: 'अगला',
		searchDocs: 'दस्तावेज़ खोजें…',
		searchPlaceholder: 'दस्तावेज़ में खोजें…',
		searchStart: 'खोजने के लिए टाइप करें',
		searchNoResults: 'कोई परिणाम नहीं',
		searchLoading: 'खोज सूचकांक लोड हो रहा है…',
		getStarted: 'शुरू करें',
		viewSource: 'स्रोत देखें',
		page: 'पेज',
		pages: 'पेज',
		builtWith: 'निर्मित',
		editOnGithub: 'GitHub पर संपादित करें',
		poweredBy: 'द्वारा संचालित',
		listAnd: 'और',
		renderingDiagram: 'डायग्राम रेंडर हो रहा है…',
		copyCode: 'कोड कॉपी करें',
		copied: 'कॉपी हो गया',
		language: 'भाषा'
	},
	bn: {
		onThisPage: 'এই পৃষ্ঠায়',
		previous: 'পূর্ববর্তী',
		next: 'পরবর্তী',
		searchDocs: 'ডকুমেন্টেশন খুঁজুন…',
		searchPlaceholder: 'ডকুমেন্টেশনে খুঁজুন…',
		searchStart: 'খুঁজতে টাইপ করুন',
		searchNoResults: 'কোনো ফলাফল নেই',
		searchLoading: 'অনুসন্ধান সূচক লোড হচ্ছে…',
		getStarted: 'শুরু করুন',
		viewSource: 'সোর্স দেখুন',
		page: 'পৃষ্ঠা',
		pages: 'পৃষ্ঠা',
		builtWith: 'নির্মিত',
		editOnGithub: 'GitHub-এ সম্পাদনা করুন',
		poweredBy: 'চালিত',
		listAnd: 'এবং',
		renderingDiagram: 'ডায়াগ্রাম রেন্ডার হচ্ছে…',
		copyCode: 'কোড কপি করুন',
		copied: 'কপি হয়েছে',
		language: 'ভাষা'
	},
	th: {
		onThisPage: 'ในหน้านี้',
		previous: 'ก่อนหน้า',
		next: 'ถัดไป',
		searchDocs: 'ค้นหาเอกสาร…',
		searchPlaceholder: 'ค้นหาในเอกสาร…',
		searchStart: 'พิมพ์เพื่อเริ่มค้นหา',
		searchNoResults: 'ไม่พบผลลัพธ์',
		searchLoading: 'กำลังโหลดดัชนีการค้นหา…',
		getStarted: 'เริ่มต้นใช้งาน',
		viewSource: 'ดูซอร์สโค้ด',
		page: 'หน้า',
		pages: 'หน้า',
		builtWith: 'สร้างด้วย',
		editOnGithub: 'แก้ไขบน GitHub',
		poweredBy: 'ขับเคลื่อนโดย',
		listAnd: 'และ',
		renderingDiagram: 'กำลังเรนเดอร์ไดอะแกรม…',
		copyCode: 'คัดลอกโค้ด',
		copied: 'คัดลอกแล้ว',
		language: 'ภาษา'
	},
	vi: {
		onThisPage: 'Trên trang này',
		previous: 'Trước',
		next: 'Tiếp',
		searchDocs: 'Tìm kiếm tài liệu…',
		searchPlaceholder: 'Tìm trong tài liệu…',
		searchStart: 'Nhập để bắt đầu tìm kiếm',
		searchNoResults: 'Không có kết quả',
		searchLoading: 'Đang tải chỉ mục tìm kiếm…',
		getStarted: 'Bắt đầu',
		viewSource: 'Xem mã nguồn',
		page: 'trang',
		pages: 'trang',
		builtWith: 'được xây dựng với',
		editOnGithub: 'Chỉnh sửa trên GitHub',
		poweredBy: 'Được hỗ trợ bởi',
		listAnd: 'và',
		renderingDiagram: 'Đang kết xuất sơ đồ…',
		copyCode: 'Sao chép mã',
		copied: 'Đã sao chép',
		language: 'Ngôn ngữ'
	},
	id: {
		onThisPage: 'Di halaman ini',
		previous: 'Sebelumnya',
		next: 'Berikutnya',
		searchDocs: 'Cari dokumentasi…',
		searchPlaceholder: 'Cari di dokumentasi…',
		searchStart: 'Ketik untuk mulai mencari',
		searchNoResults: 'Tidak ada hasil',
		searchLoading: 'Memuat indeks pencarian…',
		getStarted: 'Mulai',
		viewSource: 'Lihat sumber',
		page: 'halaman',
		pages: 'halaman',
		builtWith: 'dibuat dengan',
		editOnGithub: 'Edit di GitHub',
		poweredBy: 'Didukung oleh',
		listAnd: 'dan',
		renderingDiagram: 'Merender diagram…',
		copyCode: 'Salin kode',
		copied: 'Tersalin',
		language: 'Bahasa'
	},
	ms: {
		onThisPage: 'Pada halaman ini',
		previous: 'Sebelumnya',
		next: 'Seterusnya',
		searchDocs: 'Cari dokumentasi…',
		searchPlaceholder: 'Cari dalam dokumentasi…',
		searchStart: 'Taip untuk mula mencari',
		searchNoResults: 'Tiada keputusan',
		searchLoading: 'Memuatkan indeks carian…',
		getStarted: 'Mula',
		viewSource: 'Lihat sumber',
		page: 'halaman',
		pages: 'halaman',
		builtWith: 'dibina dengan',
		editOnGithub: 'Sunting di GitHub',
		poweredBy: 'Dikuasakan oleh',
		listAnd: 'dan',
		renderingDiagram: 'Memaparkan rajah…',
		copyCode: 'Salin kod',
		copied: 'Disalin',
		language: 'Bahasa'
	},
	ta: {
		onThisPage: 'இந்தப் பக்கத்தில்',
		previous: 'முந்தைய',
		next: 'அடுத்து',
		searchDocs: 'ஆவணங்களைத் தேடு…',
		searchPlaceholder: 'ஆவணங்களில் தேடு…',
		searchStart: 'தேட தட்டச்சு செய்யவும்',
		searchNoResults: 'முடிவுகள் இல்லை',
		searchLoading: 'தேடல் அட்டவணை ஏற்றப்படுகிறது…',
		getStarted: 'தொடங்கு',
		viewSource: 'மூலத்தைப் பார்',
		page: 'பக்கம்',
		pages: 'பக்கங்கள்',
		builtWith: 'உருவாக்கப்பட்டது',
		editOnGithub: 'GitHub-இல் திருத்து',
		poweredBy: 'இயக்குவது',
		listAnd: 'மற்றும்',
		renderingDiagram: 'வரைபடம் வழங்கப்படுகிறது…',
		copyCode: 'குறியீட்டை நகலெடு',
		copied: 'நகலெடுக்கப்பட்டது',
		language: 'மொழி'
	}
};
