// UI string translations. Merged into the catalog in ui-strings.ts.
export const dicts: Record<string, Record<string, string>> = {
	nl: {
		onThisPage: 'Op deze pagina',
		previous: 'Vorige',
		next: 'Volgende',
		searchDocs: 'Documentatie doorzoeken…',
		searchPlaceholder: 'Doorzoek de documentatie…',
		searchStart: 'Begin met typen om te zoeken.',
		searchNoResults: 'Geen resultaten',
		searchLoading: 'Zoekindex laden…',
		getStarted: 'Aan de slag',
		viewSource: 'Broncode bekijken',
		page: 'pagina',
		pages: "pagina's",
		builtWith: 'gebouwd met',
		editOnGithub: 'Bewerken op GitHub',
		poweredBy: 'Mogelijk gemaakt door',
		listAnd: 'en',
		renderingDiagram: 'Diagram weergeven…',
		copyCode: 'Code kopiëren',
		copied: 'Gekopieerd',
		language: 'Taal'
	},
	sv: {
		onThisPage: 'På den här sidan',
		previous: 'Föregående',
		next: 'Nästa',
		searchDocs: 'Sök i dokumentationen…',
		searchPlaceholder: 'Sök i dokumentationen…',
		searchStart: 'Börja skriva för att söka.',
		searchNoResults: 'Inga resultat',
		searchLoading: 'Laddar sökindex…',
		getStarted: 'Kom igång',
		viewSource: 'Visa källkod',
		page: 'sida',
		pages: 'sidor',
		builtWith: 'byggd med',
		editOnGithub: 'Redigera på GitHub',
		poweredBy: 'Drivs av',
		listAnd: 'och',
		renderingDiagram: 'Renderar diagram…',
		copyCode: 'Kopiera kod',
		copied: 'Kopierat',
		language: 'Språk'
	},
	da: {
		onThisPage: 'På denne side',
		previous: 'Forrige',
		next: 'Næste',
		searchDocs: 'Søg i dokumentationen…',
		searchPlaceholder: 'Søg i dokumentationen…',
		searchStart: 'Begynd at skrive for at søge.',
		searchNoResults: 'Ingen resultater',
		searchLoading: 'Indlæser søgeindeks…',
		getStarted: 'Kom godt i gang',
		viewSource: 'Se kildekode',
		page: 'side',
		pages: 'sider',
		builtWith: 'bygget med',
		editOnGithub: 'Rediger på GitHub',
		poweredBy: 'Drevet af',
		listAnd: 'og',
		renderingDiagram: 'Gengiver diagram…',
		copyCode: 'Kopiér kode',
		copied: 'Kopieret',
		language: 'Sprog'
	},
	nb: {
		onThisPage: 'På denne siden',
		previous: 'Forrige',
		next: 'Neste',
		searchDocs: 'Søk i dokumentasjonen…',
		searchPlaceholder: 'Søk i dokumentasjonen…',
		searchStart: 'Begynn å skrive for å søke.',
		searchNoResults: 'Ingen resultater',
		searchLoading: 'Laster søkeindeks…',
		getStarted: 'Kom i gang',
		viewSource: 'Vis kildekode',
		page: 'side',
		pages: 'sider',
		builtWith: 'bygget med',
		editOnGithub: 'Rediger på GitHub',
		poweredBy: 'Drevet av',
		listAnd: 'og',
		renderingDiagram: 'Gjengir diagram…',
		copyCode: 'Kopier kode',
		copied: 'Kopiert',
		language: 'Språk'
	},
	is: {
		onThisPage: 'Á þessari síðu',
		previous: 'Fyrri',
		next: 'Næsta',
		searchDocs: 'Leita í skjölum…',
		searchPlaceholder: 'Leitaðu í skjölunum…',
		searchStart: 'Byrjaðu að skrifa til að leita.',
		searchNoResults: 'Engar niðurstöður',
		searchLoading: 'Hleð leitarvísi…',
		getStarted: 'Hefjast handa',
		viewSource: 'Skoða frumkóða',
		page: 'síða',
		pages: 'síður',
		builtWith: 'smíðað með',
		editOnGithub: 'Breyta á GitHub',
		poweredBy: 'Keyrt af',
		listAnd: 'og',
		renderingDiagram: 'Teikna skýringarmynd…',
		copyCode: 'Afrita kóða',
		copied: 'Afritað',
		language: 'Tungumál'
	},
	tr: {
		onThisPage: 'Bu sayfada',
		previous: 'Önceki',
		next: 'Sonraki',
		searchDocs: 'Belgelerde ara…',
		searchPlaceholder: 'Belgelerde ara…',
		searchStart: 'Aramak için yazmaya başlayın.',
		searchNoResults: 'Sonuç yok',
		searchLoading: 'Arama dizini yükleniyor…',
		getStarted: 'Başlayın',
		viewSource: 'Kaynağı görüntüle',
		page: 'sayfa',
		pages: 'sayfa',
		builtWith: 'şununla oluşturuldu:',
		editOnGithub: 'GitHub\'da düzenle',
		poweredBy: 'Destekleyen:',
		listAnd: 've',
		renderingDiagram: 'Diyagram oluşturuluyor…',
		copyCode: 'Kodu kopyala',
		copied: 'Kopyalandı',
		language: 'Dil'
	},
	ar: {
		onThisPage: 'في هذه الصفحة',
		previous: 'السابق',
		next: 'التالي',
		searchDocs: 'البحث في الوثائق…',
		searchPlaceholder: 'ابحث في الوثائق…',
		searchStart: 'ابدأ الكتابة للبحث.',
		searchNoResults: 'لا توجد نتائج',
		searchLoading: 'جارٍ تحميل فهرس البحث…',
		getStarted: 'ابدأ الآن',
		viewSource: 'عرض المصدر',
		page: 'صفحة',
		pages: 'صفحات',
		builtWith: 'بُني باستخدام',
		editOnGithub: 'تحرير على GitHub',
		poweredBy: 'مدعوم من',
		listAnd: 'و',
		renderingDiagram: 'جارٍ عرض المخطط…',
		copyCode: 'نسخ الكود',
		copied: 'تم النسخ',
		language: 'اللغة'
	},
	he: {
		onThisPage: 'בעמוד זה',
		previous: 'הקודם',
		next: 'הבא',
		searchDocs: 'חיפוש בתיעוד…',
		searchPlaceholder: 'חפשו בתיעוד…',
		searchStart: 'התחילו להקליד כדי לחפש.',
		searchNoResults: 'אין תוצאות',
		searchLoading: 'טוען אינדקס חיפוש…',
		getStarted: 'בואו נתחיל',
		viewSource: 'הצגת קוד המקור',
		page: 'עמוד',
		pages: 'עמודים',
		builtWith: 'נבנה באמצעות',
		editOnGithub: 'עריכה ב‑GitHub',
		poweredBy: 'מופעל על ידי',
		listAnd: 'ו־',
		renderingDiagram: 'מעבד תרשים…',
		copyCode: 'העתקת קוד',
		copied: 'הועתק',
		language: 'שפה'
	},
	fa: {
		onThisPage: 'در این صفحه',
		previous: 'قبلی',
		next: 'بعدی',
		searchDocs: 'جستجو در مستندات…',
		searchPlaceholder: 'در مستندات جستجو کنید…',
		searchStart: 'برای جستجو شروع به تایپ کنید.',
		searchNoResults: 'نتیجه‌ای یافت نشد',
		searchLoading: 'در حال بارگذاری فهرست جستجو…',
		getStarted: 'شروع کنید',
		viewSource: 'مشاهدهٔ کد منبع',
		page: 'صفحه',
		pages: 'صفحه',
		builtWith: 'ساخته‌شده با',
		editOnGithub: 'ویرایش در GitHub',
		poweredBy: 'قدرت‌گرفته از',
		listAnd: 'و',
		renderingDiagram: 'در حال ترسیم نمودار…',
		copyCode: 'کپی کد',
		copied: 'کپی شد',
		language: 'زبان'
	}
};
