<script lang="ts">
	import '../app.css';

	import { ModeWatcher } from 'mode-watcher';
	import { afterNavigate } from '$app/navigation';
	import { base } from '$app/paths';
	import ThemeColor from '$lib/components/theme-color.svelte';
	import Lightbox from '$lib/components/lightbox.svelte';
	import TopNav from '$lib/components/top-nav.svelte';
	import Sidebar from '$lib/components/sidebar.svelte';
	import { t } from '$lib/ui-strings';
	import type { NavItem } from '$lib/nav-core';
	import type { SiteConfig } from '$lib/site';

	type Props = {
		children?: import('svelte').Snippet;
		data: { lang: string; metaPages: NavItem[]; site: SiteConfig; hasTheme: boolean };
	};
	const { children, data }: Props = $props();

	// Everything chrome-shaped (language, footer/legal links, branding)
	// arrives from the layout load — derived server-side at runtime.
	const lang = $derived(data?.lang ?? 'en');
	const metaPages = $derived(data?.metaPages ?? []);
	const siteConfig = $derived(data.site);

	// Keep <html lang> in sync on client-side navigation. The server hook
	// sets it for the initial/prerendered response (which Pagefind reads to
	// segment search); SPA navigations don't re-run that hook, so a stale
	// lang would otherwise make search use the wrong language index. $effect
	// runs only in the browser, so there's no SSR guard needed.
	$effect(() => {
		document.documentElement.lang = lang;
	});

	// The stack open-docs is built on, shown in the footer colophon.
	// Intentionally hardcoded (no config flag) so the credit ships with
	// every deployment.
	const techStack = [
		{ name: 'SvelteKit', href: 'https://svelte.dev/docs/kit' },
		{ name: 'Svelte', href: 'https://svelte.dev' },
		{ name: 'Markdoc', href: 'https://markdoc.dev' },
		{ name: 'Shiki', href: 'https://shiki.style' },
		{ name: 'Tailwind CSS', href: 'https://tailwindcss.com' },
		{ name: 'shadcn-svelte', href: 'https://shadcn-svelte.com' },
		{ name: 'Pagefind', href: 'https://pagefind.app' }
	];

	// `main` is the internal scroll container in the fixed-viewport
	// layout below, so SvelteKit's default scroll-to-top-of-window
	// after navigation is a no-op for us. afterNavigate scrolls the
	// main container itself, which is what the user actually sees,
	// otherwise clicking the Prev/Next buttons (or any sidebar link)
	// at the bottom of a long page lands the next page mid-scroll.
	let mainEl = $state<HTMLElement | null>(null);
	afterNavigate(() => {
		// A search result carries a ?highlight= term (see search.svelte). When
		// present, mark the matches on the destination page and scroll the
		// first one into view; otherwise reset the scroll to the top.
		const term = new URLSearchParams(location.search).get('highlight');
		if (term) {
			void revealSearchTerm();
		} else {
			mainEl?.scrollTo({ top: 0, behavior: 'instant' });
		}
	});

	async function revealSearchTerm() {
		try {
			// Pagefind's highlighter is generated by the production build, so it
			// only exists once the index is built. It reads the ?highlight=
			// param and wraps matches in <mark class="pagefind-highlight"> within
			// [data-pagefind-body] (our <main>). addStyles:false — the marks are
			// themed in app.css to match the in-palette search excerpts.
			// pagefind-highlight.js exposes the class as a *default* export.
			const { default: PagefindHighlight } = await import(
				/* @vite-ignore */ `${base}/pagefind/pagefind-highlight.js`
			);
			new PagefindHighlight({ highlightParam: 'highlight', addStyles: false });
		} catch {
			// Dev build (no index) — nothing to highlight.
			mainEl?.scrollTo({ top: 0, behavior: 'instant' });
			return;
		}
		// Pagefind doesn't scroll on its own; bring the first hit into view.
		requestAnimationFrame(() => {
			const first = mainEl?.querySelector('mark.pagefind-highlight');
			if (first) first.scrollIntoView({ block: 'center', behavior: 'instant' });
			else mainEl?.scrollTo({ top: 0, behavior: 'instant' });
		});
	}
</script>

<svelte:head>
	{#if data.hasTheme}
		<!-- Operator theme override (theme.css next to the content). Served at
		     runtime by /theme.css; the <link> comes after the bundled
		     stylesheet in <head>, so its rules win on equal specificity —
		     same contract as the 0.3.x build-time bundling. -->
		<link rel="stylesheet" href={`${base}/theme.css`} />
	{/if}
</svelte:head>

<ModeWatcher />
<ThemeColor />
<Lightbox />

<!-- Fixed-viewport layout. Outer container is exactly the viewport
     height; the middle row owns the remaining vertical space
     (viewport - topnav - footer). Sidebar and main each scroll
     internally inside that row, so the footer stays at the bottom
     of the viewport on short pages instead of producing an unwanted
     scrollbar past the fold. -->
<div class="flex h-screen flex-col">
	<TopNav />

	<div class="container mx-auto flex w-full max-w-screen-2xl flex-1 overflow-hidden px-4 lg:px-6">
		<aside class="hidden h-full w-64 shrink-0 border-r border-border md:block">
			<Sidebar />
		</aside>

		<main
			bind:this={mainEl}
			class="flex min-w-0 flex-1 flex-col overflow-y-auto"
			data-pagefind-body
		>
			<div class="min-w-0 flex-1">
				{@render children?.()}
			</div>

			<!-- Mobile footer: lives inside the scroll area so it slides away
			     with the content instead of pinning to the bottom of the small
			     viewport. flex-1 above pushes it to the bottom on short pages.
			     Hidden at md+, where the pinned footer below takes over.
			     data-pagefind-ignore keeps the colophon out of the search
			     index (the page body is the indexed surface). -->
			<footer
				class="border-t border-border py-4 text-xs leading-tight text-muted-foreground md:hidden"
				data-pagefind-ignore
			>
				{@render footerInner()}
			</footer>
		</main>
	</div>

	<!-- Desktop footer: pinned to the bottom of the fixed-height shell. -->
	<footer class="hidden border-t border-border py-6 text-sm text-muted-foreground md:block">
		{@render footerInner()}
	</footer>
</div>

{#snippet footerInner()}
	<div
		class="container mx-auto flex max-w-screen-2xl flex-col gap-x-6 gap-y-1 px-4 sm:flex-row sm:items-center sm:justify-between sm:gap-y-2 lg:px-6"
	>
		<div class="space-y-1">
			<p>
				{siteConfig.brandName}
				{#if siteConfig.brandTagline}{siteConfig.brandTagline}{/if},
				{t(lang, 'builtWith')}
				<a
					class="underline underline-offset-4 hover:text-foreground"
					href="https://github.com/manchtools/open-docs">open-docs</a>.
				{#if siteConfig.repoUrl}
					<a
						class="underline underline-offset-4 hover:text-foreground"
						href={siteConfig.repoUrl}
					>
						{t(lang, 'editOnGithub')}
					</a>
				{/if}
			</p>

			<!-- Legal / meta pages (frontmatter `meta: true`), e.g. an imprint
			     that some regions require. Kept out of the sidebar nav. -->
			{#if metaPages.length}
				<nav class="flex flex-wrap gap-x-3 gap-y-0.5 text-xs text-muted-foreground/80">
					{#each metaPages as m (m.href)}
						<a
							href={`${base}${m.href}`}
							class="underline-offset-4 hover:text-foreground hover:underline"
						>
							{m.label ?? m.title}
						</a>
					{/each}
				</nav>
			{/if}
		</div>

		<!-- Colophon: the stack open-docs is built on. Hardcoded into the
		     shell on purpose — there is no env flag to hide it, so it travels
		     with every deployment. Removing it means forking. -->
		<p
			class="text-[0.7rem] text-muted-foreground/70 sm:shrink-0 sm:text-right sm:text-xs sm:text-muted-foreground/80"
		>
			{t(lang, 'poweredBy')}{#each techStack as tech, i (tech.href)}{i === 0
					? ' '
					: i === techStack.length - 1
						? `, ${t(lang, 'listAnd')} `
						: ', '}<a
					class="underline-offset-4 hover:text-foreground hover:underline"
					href={tech.href}
					target="_blank"
					rel="noopener noreferrer">{tech.name}</a>{/each}.
		</p>
	</div>
{/snippet}
